config/routes.rb
Rails.application.routes.draw do
  root to: 'gardens#index'

  resources :gardens, only: %i[index show new create] do
    resources :plants, only: %i[new create]
  end

  resources :plants, only: %i[destroy] do
    # collection do
    #   get :beautiful
    # end

    # member do
    #   # get :date # /plants/:id/date => 'plants#date'
    #   # get :toggle
    # end
  end
end

# %w[one two three] => ['one', 'two', 'three']
# %i[one two three] => [:one, :two, :three]

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy

  CATEGORIES = %w[park lake antique french]

  validates :category, :name, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  validates :name, :garden, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def index
    @gardens = Garden.all
  end

  # GET /gardens/:id
  def show
    @garden = Garden.find(params[:id])
  end

  def new
    @garden = Garden.new
  end

  def create
    @garden = Garden.new(garden_params)

    render :new if !@garden.save # will render new.html.erb
  end

  private

  def garden_params
    params.require(:garden).permit(:name, :picture_url, :category)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_garden, only: %i[new create]

  # GET /gardens/:garden_id/plants/new
  def new
    @plant = Plant.new
  end

  # POST /gardens/:garden_id/plants
  def create
    @plant = Plant.new(plant_params)
    @plant.garden = @garden

    if @plant.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    redirect_to garden_path(@plant.garden)
  end

  private

  def set_garden
    @garden = Garden.find(params[:garden_id])
  end

  def plant_params
    params.require(:plant).permit(:name, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/create.html.erb
<h1>Garden was successfully created!</h1>
<p>Name: <%= @garden.name %></p>
<p>Category: <%= @garden.category %></p>

<%= link_to 'Go back', gardens_path %>

app/views/gardens/index.html.erb
<h1>My gardens</h1>

<% if notice.present? %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>

<%= link_to 'Create new garden', new_garden_path %>

<ul>
  <% @gardens.each do |garden| %>
    <li>
      <%= link_to garden.name, garden_path(garden) %>
    </li>
  <% end %>
</ul>

app/views/gardens/new.html.erb
<h1>Create new garden</h1>

<%= simple_form_for @garden do |f| %>
  <%= f.input :name %>
  <%= f.input :picture_url %>
  <%= f.input :category, collection: Garden::CATEGORIES %>
  <%= f.submit %>
<% end %>

app/views/gardens/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @garden.picture_url %>)">
  <%= @garden.name %>
</div>

<p>
  <%= link_to 'Add new plant', new_garden_plant_path(@garden), class: 'btn btn-sm btn-secondary mt-2' %>
</p>

<div class="cards">
  <% @garden.plants.each do |plant| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.picture_url %>)">
      <%= plant.name %>
      <small>
        <%= link_to '🗑', plant_path(plant), method: :delete, data: { confirm: 'Are you sure?' } %>
      </small>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plantsandgardens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/plants/date.html.erb
HELLO!!! :)

app/views/plants/new.html.erb
<h1>Add new plant</h1>

<%= simple_form_for [@garden, @plant] do |f| %>
  <%= f.input :name %>
  <%= f.input :picture_url %>
  <%= f.submit %>
<% end %>